ALTER TABLE public.clinics
  ADD COLUMN IF NOT EXISTS doctor_name TEXT,
  ADD COLUMN IF NOT EXISTS specialty   TEXT,
  ADD COLUMN IF NOT EXISTS area        TEXT,
  ADD COLUMN IF NOT EXISTS city        TEXT,
  ADD COLUMN IF NOT EXISTS address     TEXT,
  ADD COLUMN IF NOT EXISTS timings     TEXT,
  ADD COLUMN IF NOT EXISTS is_listed   BOOLEAN NOT NULL DEFAULT FALSE;